name: "[CI] L10n"
on: [push, pull_request]

env:
  CI: "true"
  CODECOV: "true"
<<<<<<< HEAD:.github/workflows/decidim-l10n.yml
=======
  DECIDIM_MODULE: decidim-l10n

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
>>>>>>> b359a9d... Generalize parts of the actions, defined node version, add concurrency to Twilio:.github/workflows/ci_decidim-l10n.yml

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD:.github/workflows/decidim-l10n.yml
          bundler-cache: true
      - run: bundle exec rake test_app
        name: Create test app
      - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
        name: Create the screenshots folder
      - uses: nanasess/setup-chromedriver@v1.0.1
      - run: cd decidim-l10n
        name: Switch to L10n sub-module
      - run: bundle exec rspec
        name: RSpec
      - uses: codecov/codecov-action@v1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
          if-no-files-found: ignore
=======
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.DECIDIM_MODULE }}
>>>>>>> b359a9d... Generalize parts of the actions, defined node version, add concurrency to Twilio:.github/workflows/ci_decidim-l10n.yml
